apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-qa

spec:
  project: default

  source:
    repoURL: https://github.com/your-repo/devsecops-platform
    targetRevision: HEAD
    path: kubernetes/overlays/qa

  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
